#!/bin/zsh

COLOR1="#130F23"
COLOR2="#8D5BD0"
A1="%{B"$COLOR2"}%{F"$COLOR1"}%{B"$COLOR1"}%{F-}"
A2="%{B"$COLOR1"}%{F"$COLOR2"}%{B"$COLOR2"}%{F-}"

clock() {
	datetime=$(date +"%d %b(%A) %H:%M")
	# echo "%{B#6c71c4}%{F#f0f0f0}  $datetime  %{B-}%{F-}"
	echo $datetime
}

cpu_load() {
	read cpu a b c previdle rest < /proc/stat
	prevtotal=$((a+b+c+previdle))
	sleep 0.5
	read cpu a b c idle rest < /proc/stat
	total=$((a+b+c+idle))
	cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
	echo CPU:$cpu%
}

cpu_temp() {
	CEL=$'\xc2\xb0C'
   	temp=$( cat /sys/devices/virtual/thermal/thermal_zone0/temp )
   	temp=`expr $temp / 1000`
   	echo TEMP:$temp$CEL
}

mem_usage() {
	mem=$(free -m | grep Mem: | awk '{print$3 / $2 * 100}')
	# echo "%{B#14eea0}%{F#232627}"
	printf "MEM: %.0f%%" $mem 
}

volume() {
	volume_level=$(pamixer --get-volume-human)
	if [ $volume_level = "muted" ]; then
		echo "%{F#ff0058}VOL: $(pamixer --get-volume)%{F-}"
	else
		echo "VOL: $volume_level"
	fi
}

while :; do
	echo "%{r}"$A2$A1$(volume)$A2$(cpu_temp)$A1$(cpu_load)$A2$(mem_usage)$A1$(clock)
	sleep 1
done
