# Don't print a new line at the start of the prompt
add_newline = false
disable_line_break = true
format = "$all"



[character]
success_symbol = "[](blue)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)" 


[battery]
disabled = true

[line_break]
disabled = true

[cmd_duration]
disabled = false
min_time = 5000
format = "[took](yellow) [$duration](bold #FF0074) "
# show_notifications = true
# min_time_to_notify = 180000

# disabling modules for
# programming languages

[golang]
disabled = true

[python]
disabled = true

[java]
disabled = true

[lua]
disabled = true

