#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar mybar &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    20
bspc config top_padding                   30
bspc config bottom_padding                -6
bspc config left_padding                  -6
bspc config right_padding                 -6
bspc config single_monocle                false
bspc config click_to_focus                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#130F23"
bspc config active_border_color	        "#BF00FF"
bspc config focused_border_color	      "#BF00FF"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a Gimp state=floating follow=on
bspc rule -a LibreWolf desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
